
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 51;
  public static final int DISTINTO = 34;
  public static final int Y = 37;
  public static final int CASO = 19;
  public static final int PORIGUAL = 40;
  public static final int ESTRUCT = 23;
  public static final int CONST = 22;
  public static final int POR = 31;
  public static final int PUNTOYCOMA = 48;
  public static final int IRA = 18;
  public static final int ENTERO = 2;
  public static final int SI = 14;
  public static final int MOSTRAR = 9;
  public static final int O = 38;
  public static final int DIVIGUAL = 41;
  public static final int HASTA = 11;
  public static final int TIPODEF = 24;
  public static final int LLLAVE = 44;
  public static final int IGUAL = 28;
  public static final int RPAR = 43;
  public static final int MASIGUAL = 39;
  public static final int SINO = 15;
  public static final int MIENTRAS = 12;
  public static final int SALTEAR = 16;
  public static final int ENCASODE = 20;
  public static final int DIV = 32;
  public static final int RLLAVE = 45;
  public static final int CONTINUAR = 17;
  public static final int NUM = 26;
  public static final int ID = 25;
  public static final int RETORNO = 8;
  public static final int EOF = 0;
  public static final int DECIMAL = 3;
  public static final int error = 1;
  public static final int COMA = 49;
  public static final int CADENA = 27;
  public static final int MENOS = 30;
  public static final int MENOR = 35;
  public static final int ASIGNACION = 52;
  public static final int LBRACK = 46;
  public static final int MAYOR = 36;
  public static final int PUNTO = 50;
  public static final int VACIO = 6;
  public static final int RBRACK = 47;
  public static final int IGUALIGUAL = 33;
  public static final int HACER = 13;
  public static final int BOOLEANO = 5;
  public static final int LPAR = 42;
  public static final int PARA = 10;
  public static final int INICIO = 7;
  public static final int TEXTO = 4;
  public static final int DEFECTO = 21;
  public static final int MAS = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "DECIMAL",
  "TEXTO",
  "BOOLEANO",
  "VACIO",
  "INICIO",
  "RETORNO",
  "MOSTRAR",
  "PARA",
  "HASTA",
  "MIENTRAS",
  "HACER",
  "SI",
  "SINO",
  "SALTEAR",
  "CONTINUAR",
  "IRA",
  "CASO",
  "ENCASODE",
  "DEFECTO",
  "CONST",
  "ESTRUCT",
  "TIPODEF",
  "ID",
  "NUM",
  "CADENA",
  "IGUAL",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "IGUALIGUAL",
  "DISTINTO",
  "MENOR",
  "MAYOR",
  "Y",
  "O",
  "MASIGUAL",
  "PORIGUAL",
  "DIVIGUAL",
  "LPAR",
  "RPAR",
  "LLLAVE",
  "RLLAVE",
  "LBRACK",
  "RBRACK",
  "PUNTOYCOMA",
  "COMA",
  "PUNTO",
  "DOSPUNTOS",
  "ASIGNACION"
  };
}

